# ===========================================
# Site Information Settings
# ===========================================

# Site creation time
since: 2014

# Custom your favicon.ico in `site/source`
favicon: /favicon.ico

# Set feed link (false | default | your feed link)
# false: disable
# default: use `atom.xml`, generator for `hexo-generator-feed`
rss: default

# ===========================================
# Menu Settings
# ===========================================
menu:
  Archives: /archives
  About: /about

# ===========================================
# Widget Settings
# ===========================================
# widget function
# false: disable
# widget_custom: custom your widget
#   title: your widget title
#   content: Add your html code in here. Example: <p>Hello, I am Frost</p>
widget:
  Tags: true
  Categories: false

widget_custom:
    title:
    content:

# ===========================================
# Theme Settings
# ===========================================
# theme styling
# color: Default | Mint Green | Cobalt Blue | Hot Pink | Dark Violet
theme:
  color: Default
  fancybox: false

# ===========================================
# Third Party Services Settings
# ===========================================

# Baidu Analytics
baidu_analytics:
# Google Analytics
google_analytics:

# Duoshuo
duoshuo_shortname:
# Disqus
disqus_shortname:


# ===========================================
# Version
# ===========================================
version: 1.1
